name: _cleanup-test-ghcr-tag

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  delete-test-tag:
    runs-on: ubuntu-latest
    steps:
      - name: delete jochona-beacon test package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          gh api -X DELETE /orgs/jochona/packages/container/jochona-beacon
